### PR TITLE
Cursor pagination

### PR DESCRIPTION
**Pull request by panzer-punk**
Added cursor pagination based on search_after.

### CODE REVIEW

**Comment by daannet** [comment]
@Gsuper36 Thank you for your contribution! 

I'm a huge proponent of cursor pagination. Perhaps we should add a note that data sorting is required and therefore no relevance sorting can be applied when using cursor pagination.

**Comment by panzer-punk** [comment]
@daannet Agree, I'll expand documentation about cursor pagination.

**Comment by panzer-punk** [comment]
@daannet 

I'm looking forward to add sort modes, nested and geo_distance sorting. Should we hold this PR until it's done or should we split it in two PRs?

**Comment by daannet** [comment]
@Gsuper36 I'm merging this PR to keep track of the specific changes.

**Pull request merged**
